-- Departamentos
INSERT INTO departamento (id_departamento, nombre) VALUES (1, 'Alta Verapaz');
INSERT INTO departamento (id_departamento, nombre) VALUES (2, 'Baja Verapaz');
INSERT INTO departamento (id_departamento, nombre) VALUES (3, 'Chimaltenango');
INSERT INTO departamento (id_departamento, nombre) VALUES (4, 'Chiquimula');
INSERT INTO departamento (id_departamento, nombre) VALUES (5, 'El Progreso');
INSERT INTO departamento (id_departamento, nombre) VALUES (6, 'Escuintla');
INSERT INTO departamento (id_departamento, nombre) VALUES (7, 'Guatemala');
INSERT INTO departamento (id_departamento, nombre) VALUES (8, 'Huehuetenango');
INSERT INTO departamento (id_departamento, nombre) VALUES (9, 'Izabal');
INSERT INTO departamento (id_departamento, nombre) VALUES (10, 'Jalapa');
INSERT INTO departamento (id_departamento, nombre) VALUES (11, 'Jutiapa');
INSERT INTO departamento (id_departamento, nombre) VALUES (12, 'Petén');
INSERT INTO departamento (id_departamento, nombre) VALUES (13, 'Quetzaltenango');
INSERT INTO departamento (id_departamento, nombre) VALUES (14, 'Quiché');
INSERT INTO departamento (id_departamento, nombre) VALUES (15, 'Retalhuleu');
INSERT INTO departamento (id_departamento, nombre) VALUES (16, 'Sacatepéquez');
INSERT INTO departamento (id_departamento, nombre) VALUES (17, 'San Marcos');
INSERT INTO departamento (id_departamento, nombre) VALUES (18, 'Santa Rosa');
INSERT INTO departamento (id_departamento, nombre) VALUES (19, 'Sololá');
INSERT INTO departamento (id_departamento, nombre) VALUES (20, 'Suchitepéquez');
INSERT INTO departamento (id_departamento, nombre) VALUES (21, 'Totonicapán');
INSERT INTO departamento (id_departamento, nombre) VALUES (22, 'Zacapa');

-- Municipios
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (1, 1, 'Chahal');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (1, 2, 'Lanquín');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (1, 3, 'San Juan Chamelco');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (1, 4, 'Santa María Cahabón');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (1, 5, 'Tucurú');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (1, 6, 'Chisec');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (1, 7, 'Panzós');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (1, 8, 'San Pedro Carchá');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (1, 9, 'Senahú');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (1, 10, 'Cobán');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (1, 11, 'Raxruhá');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (1, 12, 'Santa Catalina La Tinta');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (1, 13, 'Tactic');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (1, 14, 'Fray Bartolomé de las Casas');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (1, 15, 'San Cristóbal Verapaz');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (1, 16, 'Santa Cruz Verapaz');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (1, 17, 'Tamahú');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (2, 18, 'Cubulco');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (2, 19, 'Salamá');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (2, 20, 'Granados');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (2, 21, 'San Jerónimo');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (2, 22, 'Purulhá');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (2, 23, 'San Miguel Chicaj');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (2, 24, 'Rabinal');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (2, 25, 'Santa Cruz el Chol');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (3, 26, 'Acatenango');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (3, 27, 'Patzicía');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (3, 28, 'San José Poaquil');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (3, 29, 'Santa Cruz Balanyá');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (3, 30, 'Chimaltenango');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (3, 31, 'Patzún');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (3, 32, 'San Juan Comalapa');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (3, 33, 'Tecpán');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (3, 34, 'El Tejar');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (3, 35, 'Pochuta');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (3, 36, 'San Martín Jilotepeque');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (3, 37, 'Yepocapa');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (3, 38, 'Parramos');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (3, 39, 'San Andrés Itzapa');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (3, 40, 'Santa Apolonia');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (3, 41, 'Zaragoza');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (4, 42, 'Camotán');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (4, 43, 'Ipala');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (4, 44, 'San Jacinto');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (4, 45, 'Chiquimula');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (4, 46, 'Jocotán');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (4, 47, 'San José La Arada');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (4, 48, 'Concepción Las Minas');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (4, 49, 'Olopa');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (4, 50, 'San Juan Ermita');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (4, 51, 'Esquipulas');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (4, 52, 'Quezaltepeque');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (5, 53, 'El Jícaro');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (5, 54, 'San Antonio La Paz');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (5, 55, 'Guastatoya');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (5, 56, 'San Cristóbal Acasaguastlán');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (5, 57, 'Morazán');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (5, 58, 'Sanarate');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (5, 59, 'San Agustín Acasaguastlán');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (5, 60, 'Sansare');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (6, 61, 'Escuintla');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (6, 62, 'La Gomera');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (6, 63, 'San José');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (6, 64, 'Tiquisate');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (6, 65, 'Guanagazapa');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (6, 66, 'Masagua');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (6, 67, 'San Vicente Pacaya');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (6, 68, 'Iztapa');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (6, 69, 'Nueva Concepción');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (6, 70, 'Santa Lucía Cotzumalguapa');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (6, 71, 'La Democracia');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (6, 72, 'Palín');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (6, 73, 'Siquinalá');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (7, 74, 'Amatitlán');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (7, 75, 'Guatemala');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (7, 76, 'San José Pinula');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (7, 77, 'San Pedro Sacatepéquez');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (7, 78, 'Villa Nueva');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (7, 79, 'Chinautla');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (7, 80, 'Mixco');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (7, 81, 'San Juan Sacatepéquez');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (7, 82, 'San Raymundo');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (7, 83, 'Chuarrancho');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (7, 84, 'Palencia');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (7, 85, 'San Miguel Petapa');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (7, 86, 'Santa Catarina Pinula');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (7, 87, 'Fraijanes');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (7, 88, 'San José del Golfo');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (7, 89, 'San Pedro Ayampuc');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (7, 90, 'Villa Canales');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (8, 91, 'Aguacatán');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (8, 92, 'Cuilco');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (8, 93, 'La Libertad');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (8, 94, 'San Gaspar Ixchil');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (8, 95, 'San Mateo Ixtatán');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (8, 96, 'San Rafael La Independencia');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (8, 97, 'Santa Ana Huista');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (8, 98, 'Santiago Chimaltenango');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (8, 99, 'Chiantla');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (8, 100, 'Huehuetenango');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (8, 101, 'Malacatancito');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (8, 102, 'San Ildefonso Ixtahuacán');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (8, 103, 'San Miguel Acatán');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (8, 104, 'San Rafael Petzal');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (8, 105, 'Santa Bárbara');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (8, 106, 'Tectitán');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (8, 107, 'Colotenango');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (8, 108, 'Jacaltenango');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (8, 109, 'Nentón');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (8, 110, 'San Juan Atitán');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (8, 111, 'San Pedro Necta');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (8, 112, 'San Sebastián Coatán');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (8, 113, 'Santa Cruz Barillas');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (8, 114, 'Todos Santos Cuchumatánes');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (8, 115, 'Concepción Huista');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (8, 116, 'La Democracia');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (8, 117, 'San Antonio Huista');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (8, 118, 'San Juan Ixcoy');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (8, 119, 'San Pedro Soloma');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (8, 120, 'San Sebastián');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (8, 121, 'Santa Eulalia');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (8, 122, 'Unión Cantinil');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (9, 123, 'El Estor');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (9, 124, 'Puerto Barrios');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (9, 125, 'Livingston');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (9, 126, 'Los Amates');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (9, 127, 'Morales');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (10, 128, 'Jalapa');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (10, 129, 'San Luis Jilotepeque');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (10, 130, 'Mataquescuintla');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (10, 131, 'San Manuel Chaparrón');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (10, 132, 'Monjas');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (10, 133, 'San Pedro Pinula');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (10, 134, 'San Carlos Alzatate');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (11, 135, 'Agua Blanca');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (11, 136, 'Conguaco');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (11, 137, 'Jerez');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (11, 138, 'Quesada');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (11, 139, 'Zapotitlán');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (11, 140, 'Asunción Mita');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (11, 141, 'El Adelanto');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (11, 142, 'Jutiapa');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (11, 143, 'San José Acatempa');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (11, 144, 'Atescatempa');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (11, 145, 'El Progreso');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (11, 146, 'Moyuta');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (11, 147, 'Santa Catarina Mita');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (11, 148, 'Comapa');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (11, 149, 'Jalpatagua');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (11, 150, 'Pasaco');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (11, 151, 'Yupiltepeque');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (12, 152, 'Dolores');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (12, 153, 'Melchor de Mencos');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (12, 154, 'San Francisco');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (12, 155, 'Sayaxché');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (12, 156, 'Flores');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (12, 157, 'Poptún');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (12, 158, 'San José');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (12, 159, 'La Libertad');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (12, 160, 'San Andrés');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (12, 161, 'San Luis');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (12, 162, 'Las Cruces');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (12, 163, 'San Benito');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (12, 164, 'Santa Ana');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (13, 165, 'Almolonga');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (13, 166, 'Coatepeque');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (13, 167, 'Flores Costa Cuca');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (13, 168, 'Olintepeque');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (13, 169, 'San Carlos Sija');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (13, 170, 'San Mateo');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (13, 171, 'Cabricán');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (13, 172, 'Colomba');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (13, 173, 'Génova');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (13, 174, 'Palestina de Los Altos');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (13, 175, 'San Francisco La Unión');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (13, 176, 'San Miguel Sigüilá');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (13, 177, 'Cajolá');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (13, 178, 'Concepción Chiquirichapa');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (13, 179, 'Huitán');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (13, 180, 'Quetzaltenango');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (13, 181, 'San Juan Ostuncalco');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (13, 182, 'Sibilia');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (13, 183, 'Cantel');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (13, 184, 'El Palmar');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (13, 185, 'La Esperanza');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (13, 186, 'Salcajá');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (13, 187, 'San Martín Sacatepéquez');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (13, 188, 'Zunil');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (14, 189, 'Canillá');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (14, 190, 'Chichicastenango');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (14, 191, 'Joyabaj');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (14, 192, 'Sacapulas');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (14, 193, 'San Juan Cotzal');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (14, 194, 'Zacualpa');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (14, 195, 'Chajul');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (14, 196, 'Chinique');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (14, 197, 'Nebaj');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (14, 198, 'San Andrés Sajcabajá');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (14, 199, 'San Pedro Jocopilas');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (14, 200, 'Chicamán');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (14, 201, 'Cunén');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (14, 202, 'Pachalum');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (14, 203, 'San Antonio Ilotenango');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (14, 204, 'Santa Cruz del Quiché');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (14, 205, 'Chiché');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (14, 206, 'Ixcán');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (14, 207, 'Patzité');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (14, 208, 'San Bartolomé Jocotenango');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (14, 209, 'Uspantán');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (15, 210, 'Champerico');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (15, 211, 'San Andrés Villa Seca');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (15, 212, 'Santa Cruz Muluá');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (15, 213, 'El Asintal');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (15, 214, 'San Felipe');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (15, 215, 'Nuevo San Carlos');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (15, 216, 'San Martín Zapotitlán');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (15, 217, 'Retalhuleu');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (15, 218, 'San Sebastián');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (16, 219, 'Alotenango');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (16, 220, 'Magdalena Milpas Altas');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (16, 221, 'San Lucas Sacatepéquez');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (16, 222, 'Santa María de Jesús');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (16, 223, 'La Antigua Guatemala');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (16, 224, 'Pastores');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (16, 225, 'San Miguel Dueñas');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (16, 226, 'Santiago Sacatepéquez');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (16, 227, 'Ciudad Vieja');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (16, 228, 'San Antonio Aguas Calientes');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (16, 229, 'Santa Catarina Barahona');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (16, 230, 'Santo Domingo Xenacoj');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (16, 231, 'Jocotenango');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (16, 232, 'San Bartolomé Milpas Altas');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (16, 233, 'Santa Lucía Milpas Altas');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (16, 234, 'Sumpango');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (17, 235, 'Ayutla');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (17, 236, 'El Quetzal');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (17, 237, 'Ixchiguán');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (17, 238, 'Ocós');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (17, 239, 'San Cristóbal Cucho');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (17, 240, 'San Miguel Ixtahuacán');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (17, 241, 'Sibinal');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (17, 242, 'Tejutla');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (17, 243, 'Catarina');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (17, 244, 'El Rodeo');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (17, 245, 'La Reforma');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (17, 246, 'Pajapita');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (17, 247, 'San José Ojetenam');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (17, 248, 'San Pablo');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (17, 249, 'Sipacapa');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (17, 250, 'Comitancillo');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (17, 251, 'El Tumbador');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (17, 252, 'Malacatán');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (17, 253, 'Río Blanco');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (17, 254, 'San Lorenzo');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (17, 255, 'San Pedro Sacatepéquez');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (17, 256, 'Tacaná');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (17, 257, 'Concepción Tutuapa');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (17, 258, 'Esquipulas Palo Gordo');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (17, 259, 'Nuevo Progreso');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (17, 260, 'San Antonio Sacatepéquez');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (17, 261, 'San Marcos');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (17, 262, 'San Rafael Pie de La Cuesta');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (17, 263, 'Tajumulco');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (18, 264, 'Barberena');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (18, 265, 'Guazacapán');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (18, 266, 'San Juan Tecuaco');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (18, 267, 'Santa Rosa de Lima');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (18, 268, 'Casillas');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (18, 269, 'Nueva Santa Rosa');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (18, 270, 'San Rafaél Las Flores');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (18, 271, 'Taxisco');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (18, 272, 'Chiquimulilla');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (18, 273, 'Oratorio');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (18, 274, 'Santa Cruz Naranjo');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (18, 275, 'Cuilapa');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (18, 276, 'Pueblo Nuevo Viñas');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (18, 277, 'Santa María Ixhuatán');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (19, 278, 'Concepción');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (19, 279, 'San Antonio Palopó');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (19, 280, 'San Marcos La Laguna');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (19, 281, 'Santa Catarina Palopó');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (19, 282, 'Santa María Visitación');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (19, 283, 'Nahualá');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (19, 284, 'San José Chacayá');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (19, 285, 'San Pablo La Laguna');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (19, 286, 'Santa Clara La Laguna');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (19, 287, 'Santiago Atitlán');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (19, 288, 'Panajachel');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (19, 289, 'San Juan La Laguna');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (19, 290, 'San Pedro La Laguna');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (19, 291, 'Santa Cruz La Laguna');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (19, 292, 'Sololá');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (19, 293, 'San Andrés Semetabaj');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (19, 294, 'San Lucas Tolimán');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (19, 295, 'Santa Catarina Ixtahuacan');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (19, 296, 'Santa Lucía Utatlán');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (20, 297, 'Chicacao');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (20, 298, 'Pueblo Nuevo');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (20, 299, 'San Bernardino');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (20, 300, 'San Juan Bautista');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (20, 301, 'Santa Bárbara');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (20, 302, 'Cuyotenango');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (20, 303, 'Río Bravo');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (20, 304, 'San Francisco Zapotitlán');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (20, 305, 'San Lorenzo');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (20, 306, 'Santo Domingo');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (20, 307, 'Mazatenango');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (20, 308, 'Samayac');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (20, 309, 'San Gabriel');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (20, 310, 'San Miguel Panán');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (20, 311, 'Santo Tomás La Unión');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (20, 312, 'Patulul');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (20, 313, 'San Antonio');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (20, 314, 'San José El Ídolo');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (20, 315, 'San Pablo Jocopilas');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (20, 316, 'Zunilito');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (21, 317, 'Momostenango');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (21, 318, 'San Francisco El Alto');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (21, 319, 'San Andrés Xecul');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (21, 320, 'Santa Lucía La Reforma');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (21, 321, 'San Bartolo');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (21, 322, 'Santa María Chiquimula');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (21, 323, 'San Cristóbal Totonicapán');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (21, 324, 'Totonicapán');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (22, 325, 'Cabañas');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (22, 326, 'La Unión');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (22, 327, 'Usumatlán');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (22, 328, 'Estanzuela');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (22, 329, 'Río Hondo');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (22, 330, 'Zacapa');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (22, 331, 'Gualán');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (22, 332, 'San Diego');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (22, 333, 'Huité');
INSERT INTO municipio (id_departamento, id_municipio, nombre) VALUES (22, 334, 'Teculután');